 select * from customer;

#Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);


#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS Number_of_Customers
from customer_type 
group by customer_segment;

#Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#10. What is the revenue contribution of each age group? 
SELECT 
    age_grouped,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_grouped
ORDER BY total_revenue DESC;

#11. How does total purchase amount vary across different locations?
select location, sum(purchase_amount) as total_purchase_amount
from customer
group by location
order by total_purchase_amount DESC
limit 10;

#12. Which location has the highest average purchase amount per customer?
select location, avg(purchase_amount) as avg_purchase_amount
from customer
group by location
order by avg_purchase_amount DESC
limit 5;




#13. What is the distribution of customers across age groups in each location?
select count(customer_id) as customer_count, age_grouped, location
from customer
group by location, age_grouped
order by customer_count DESC
limit 12;




#14. Do customers from different locations show different preferences for shipping type?
select count(customer_id) as customer_count, location, shipping_type
from customer
group by shipping_type, location
order by customer_count DESC
limit 10;




#15. Which locations have the highest proportion of subscribed customers?
select location, count(subscription_status) as subscribed_customers
from customer
where subscription_status = 'Yes'
group by location
order by subscribed_customers desc;



#16. How does average review rating vary by age group and location?
select round(avg(review_rating), 2) as avg_review_rating, age_grouped, location
from customer
group by age_grouped, location
order by avg_review_rating DESC;



#17. Are customers in certain locations more likely to use discounts?
select count(customer_id) as customer_count, location, discount_applied
from customer
where discount_applied = 'Yes'
group by location
order by customer_count DESC;



#18. Which payment methods are most popular in each location?
select payment_method, location, payment_count
from (
	Select payment_method, 
			location, count(*) as payment_count,
			row_number() over(
							partition by location 
							order by count(*)
							) as rn
        from customer
        group by location, payment_method
        order by payment_count desc
) t
where rn = 1
limit 10;



#19. How does spending behavior differ between age groups?
select age_grouped, avg(purchase_amount) as avg_purchase_amt, sum(purchase_amount) as total_purchase_amt
from customer
group by age_grouped
order by avg_purchase_amt desc;



#20. Which age group contributes the most total revenue?
select age_grouped, sum(purchase_amount) as total_purchase_amt
from customer
group by age_grouped;



#21. Do certain genders show higher purchase frequency?
select gender, frequency_of_purchases, count(*) as customer_count
from customer
group by gender, frequency_of_purchases
order by customer_count;



#22. How does purchase frequency differ between subscribed and non-subscribed customers?
select subscription_status, frequency_of_purchases, count(*) as customer_count
from customer
group by subscription_status, frequency_of_purchases
order by customer_count;



#23. How does seasonal purchasing behavior vary by location?
select location, season, round(avg(purchase_amount), 2) as avg_purchasing_amt
from customer
group by location, season
order by location, avg_purchasing_amt desc;



#24. Which season generates the highest revenue for each age group?
select season, age_grouped, revenue
from(
	select season, age_grouped, sum(purchase_amount) as revenue,
    row_number() over(
						partition by age_grouped
                        order by sum(purchase_amount) desc
                        ) as rn
	from customer
    group by age_grouped, season
) t
where rn = 1;



#25. Which age group has the highest number of loyal customers based on previous purchases?
SELECT 
    age_grouped,
    COUNT(*) AS loyal_customers,
    SUM(purchase_amount) AS total_loyal_revenue
FROM customer
WHERE previous_purchases >= 10
GROUP BY age_grouped
ORDER BY loyal_customers DESC;



#26. Are customers with higher purchase frequency more likely to leave higher review ratings?
select frequency_of_purchases, count(*) as customer_count, Round(avg(review_rating), 2) as avg_review_rating
from customer
group by frequency_of_purchases
order by avg_review_rating desc;



#27. Which product categories generate the highest total revenue?
select category, sum(purchase_amount) as total_revenue
from customer
group by category
order by total_revenue desc;



#28. Which products have the highest repeat purchase rate based on previous purchases?
select item_purchased, count(case when previous_purchases > 1 then 1 end)*100/count(*) as repeat_purchase_rate
from customer
group by item_purchased
order by repeat_purchase_rate desc;




#29. Which product categories receive the lowest average review ratings?
select category, round(avg(review_rating), 2) as avg_review_rating,
rank() over(order by avg(review_rating)) as customer_rank
from customer
group by category
order by customer_rank;




#30. Which locations generate the highest total revenue?
select location, sum(purchase_amount) as total_revenue
from customer
group by location
order by total_revenue desc ;



#31.Which locations have the highest proportion of discounted purchases?
select location, sum(case when discount_applied = 'Yes' then 1 end) * 100/count(*) as discount_purchase
from customer
group by location
order by discount_purchase;



#32. How does seasonality impact total revenue across locations?
with season_revenue as(
select season, location, sum(purchase_amount) as total_revenue,
rank() over(partition by season order by sum(purchase_amount)) as season_rank
from customer
group by season, location
)
select season, location, total_revenue, season_rank
from season_revenue
where season_rank <= 5
order by season, season_rank;



#33.What percentage of orders uses each shipping type?
select shipping_type, count(*) as total_orders, round(count(*) *100 / (select count(*) from customer), 2) as percentage_of_order
from customer
group by shipping_type
order by total_orders;



#34. Which shipping type is associated with higher review ratings?
select shipping_type, round(avg(review_rating), 2) as avg_review_rating
from customer
group by shipping_type
order by avg_review_rating desc;



#35. What is the overall distribution of payment methods?
select payment_method, count(*) as total_order
from customer
group by payment_method
order by total_order desc;



#36. Which payment methods are associated with the highest average purchase amount?
select payment_method, avg(purchase_amount) as avg_purchase_amt
from customer
group by payment_method
order by avg_purchase_amt desc;




#37. Are certain payment methods more commonly used for discounted purchases?
with payment_stat as(
select payment_method, count(*)total_order, sum(case when discount_applied = 'Yes' then 1 end) as discount_orders
from customer
group by payment_method
)
select payment_method, discount_orders, total_order, round(discount_orders * 100 / total_order, 2) as percent_discount
from payment_stat
order by percent_discount desc;



#38. Do discounted purchases result in higher purchase frequency?
select frequency_of_purchases,
		count(*) total_order, 
		sum(case when discount_applied = 'Yes' then 1 end) as discounted_purchases, 
        round(sum(case when discount_applied = 'Yes' then 1 end)* 100/ count(*),2) as percent_discount
from customer
group by frequency_of_purchases
order by discounted_purchases desc;

#39. Which product sizes are purchased the most?
select size, count(*) as total_orders
from customer
group by size;

#40. Which size generates the highest average purchase amount?
select size, count(*) as total_orders, round(avg(purchase_amount),2) as avg_purchase_amt
from customer
group by size
order by avg_purchase_amt desc;

#41. Which size has the highest repeat purchase rate and average review rating?
select size, 
		round(avg(review_rating),2) as avg_review_rating, 
        round(sum(case when previous_purchases >= 1 then 1 end) * 100 / count(*), 2) as purchase_rate
from customer
group by size
order by avg_review_rating desc, purchase_rate desc;


#42. Which products generate high revenue?
select item_purchased, sum(purchase_amount) as revenue
from customer
group by item_purchased
order by revenue desc
limit 5;

#43. Which products generate high revenue but low customer satisfaction?
select item_purchased, purchase_amount, review_rating 
from customer
where purchase_amount >= (select avg(purchase_amount) from customer) 
AND review_rating <= (select avg(review_rating) from customer) ;

#44. Which combinations of product category and shipping type generate the highest revenue?
select category, shipping_type, Sum(purchase_amount) as revenue
from customer
group by  category, shipping_type
order by revenue desc;


#45. Which size and color combinations generate the highest revenue and highest customer satisfaction?
select size, color, sum(purchase_amount) as revenue, round(avg(review_rating),2) as customer_satisfaction
from customer
group by size, color
order by revenue desc, customer_satisfaction desc;



#46. What is the top 5 average review rating based on location
select round(avg(review_rating),2) as avg_review_rating, location
from customer
group by location
order by avg_review_rating desc
limit 5;

#47. What is the top 5 average review rating based on category
select round(avg(review_rating),2) as avg_review_rating, category
from customer
group by category
order by avg_review_rating desc
limit 5;


#48. What is the average review rating 
select round(avg(review_rating),2) as avg_review_rating
from customer;


#49. What is the top 5 average revenue based on category
select round(avg(purchase_amount),2) as avg_review_rating, category
from customer
group by category
order by avg_review_rating desc
limit 5;


#50. What is the top 5 average revenue based on location
select round(avg(purchase_amount),2) as avg_revenue, location
from customer
group by location
order by avg_revenue desc
limit 5;

#51. What is the average revenue
select round(avg(purchase_amount),2) as avg_revenue
from customer;


#52. What is the total revenue
select round(sum(purchase_amount),2) as avg_revenue
from customer;