select * from customer;

#Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);


#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

#Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#10. What is the revenue contribution of each age group? 
SELECT 
    age_grouped,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_grouped
ORDER BY total_revenue DESC;

#11. How does total purchase amount vary across different locations?
select location, sum(purchase_amount) as total_purchase_amount
from customer
group by location
order by total_purchase_amount DESC;

#12. Which location has the highest average purchase amount per customer?
select location, avg(purchase_amount) as avg_purchase_amount
from customer
group by location
order by avg_purchase_amount DESC
limit 5;


select * from customer;
#13. What is the distribution of customers across age groups in each location?
select count(customer_id) as customer_count, age_grouped, location
from customer
group by location, age_grouped
order by customer_count DESC;

select * from customer;
#14. Do customers from different locations show different preferences for shipping type?
select count(customer_id) as customer_count, location, shipping_type
from customer
group by shipping_type, location
order by customer_count DESC
limit 10;

select * from customer;
#15. Which locations have the highest proportion of subscribed customers?
select location, count(subscription_status) as subscribed_customers
from customer
where subscription_status = 'Yes'
group by location
order by subscribed_customers desc;

select * from customer;
#16. How does average review rating vary by age group and location?
select round(avg(review_rating), 2) as avg_review_rating, age_grouped, location
from customer
group by age_grouped, location
order by avg_review_rating DESC;


select * from customer;
#17. Are customers in certain locations more likely to use discounts?
select count(customer_id) as customer_count, location, discount_applied
from customer
where discount_applied = 'Yes'
group by location
order by customer_count DESC;


select * from customer;
#18. Which payment methods are most popular in each location?
select location, payment_method, payment_count
from (select location, payment_method, count(*)as payment_count,
		row_number() over(partition by location
							order by count(*) desc) as rn
	from customer
    group by location, payment_method
    ) t
    where rn = 1
